default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: newblog_development

test:
  <<: *default
  database: newblog_test

production:
  <<: *default
  database: newblog_production
  username: newblog
  password: <%= ENV['NEWBLOG_DATABASE_PASSWORD'] %>
